[book]
title = "ğŸ suda-morris ä¸ªäººåšå®¢ ğŸ‡"
authors = ["suda-morris"]
description = "Personal Blog"
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true

[rust]
edition = "2021" # the default edition for code blocks
